name: Deploy Logic App

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master","dev","main" ]
  pull_request:
    branches: [ "master" ]

env:
  Bicep_path: "/master/AzureIntegration/KeyVault/pipeline/logicappcreation.bicep"
  parameters_path: "/master/AzureIntegration/KeyVault/pipeline/parameters.json"
  outputFilePath: "/master/main/AzureIntegration/KeyVault/pipeline/"
  DEPLOYMENT_NAME: GH_CICD_${{ github.run_id }}
  AZ_OBJECT_ID: ${{ secrets.AZ_OBJECT_ID}}
  AZ_RG_NM: ${{ secrets.AZ_RG_NM}}
  AZ_RGS_NM: "azintegration"

  # Setting Github what permissions this workflow needs
  permissions:
  id-token: write
  contents: read
  deployments: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bicep

    - name: Deploy Logic App
      uses: azure/bicep@0.1.3
      with:
        args: deploy -n mylogicapp -g myresourcegroup -f main.bicep
